---
- name: 'Ensure {{ postgresql_service }} running'
  ansible.builtin.systemd_service:
    name: '{{ postgresql_service }}'
    state: restarted
    enabled: true
  become_user: root
  become_method: sudo

- name: Query database for user API_KEY 
  become: true
  become_user: postgres
  postgresql_query:
    db: galaxy
    login_user: postgres
    query: SELECT exists (SELECT key FROM api_keys WHERE '"{{ GALAXY_ADMIN_API_KEY }}"' LIKE '%' || key || '%');
  register: result
  ignore_errors: yes  

- name: Download user creation script 
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/python3/galaxy_tools/py3_manage_bootstrap_user.py
    dest: "{{ laniakea_galaxy_server_dir }}/manage_bootstrap_user.py"
    mode: 0755
  when: result.failed or not result.query_result[0].exists

- name: Get Password from vault
  set_fact:
    GALAXY_ADMIN_PASSWORD: '{{ vault_secrets.data.admin_password }}'
  no_log: True
  when: retrieve_passphrase_from_vault

- name: Create random admin user api key
  set_fact:
    GALAXY_ADMIN_API_KEY: "{{ lookup('community.general.random_string', length=50, special=false) }}"
  no_log: True
  when: galaxy_admin_api_key == "random"

- name: Set custom admin user api key
  set_fact:
    GALAXY_ADMIN_API_KEY: "{{ galaxy_admin_api_key }}"
  no_log: True
  when: galaxy_admin_api_key != "random"

- name: Create galaxy user with API_KEY to install tools
  shell:
    cmd: '. {{ laniakea_galaxy_venv_dir }}/bin/activate; 
          python3 manage_bootstrap_user.py
          -c {{ laniakea_galaxy_config_file }} create
          -u {{ GALAXY_ADMIN_USERNAME }}
          -e {{ GALAXY_ADMIN_EMAIL }}
          -p {{ GALAXY_ADMIN_PASSWORD }}
          -a {{ GALAXY_ADMIN_API_KEY }}'
    chdir: "{{ laniakea_galaxy_server_dir }}"
  when: result.failed or not result.query_result[0].exists
