---

- name: Ensure sudo no password for galaxy user
  lineinfile:
    path: /etc/sudoers
    state: present
    line: galaxy ALL=(ALL) NOPASSWD:ALL
  
- name: create/check destinations
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: '{{ laniakea_galaxy_user }}'
    group: '{{ laniakea_galaxy_group }}'
  with_items:
    - "{{ export_dir }}"
    - "{{ tool_deps_path }}"
    - "{{ shed_tool_destination }}"
