---
# Restart services
# Postgresql already up and running for user configuration

#- name: Restart proftpd
#  systemd:
#    name: proftpd
#    state: restarted

- name: Restart and enable NGINX
  systemd:
    name: nginx
    state: restarted
    enabled: true

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Restart docker
  systemd:
    name: docker
    state: restarted
  when: enable_interactive_tools
