---
# tasks file for ansible-role-lanikea-restore

- name: Ensure Galaxy is stopped
  debug:
    msg: "Placeholder galaxyctl stop"

- include: configure_os.yml
  become: yes

### Always configure cvmfs and galaxyproject.org repository   
- name: CVMFS
  include_role:
    name: galaxyproject.cvmfs
  vars:
    cvmfs_role: client
    galaxy_cvmfs_repos_enabled: config-repo

### Configure Galaxy
- include: configure_galaxy.yml

### install proftpd
#- include: proftpd.yml
#  become: yes
#  become_user: root

### install laniakea utils
#- name: Install laniakea-utils
#  include_role:
#    name: laniakea.laniakea_utils

### Create Galaxy administrator
- name: create admin user
  include: admin_user.yml
  become: true
  become_user: galaxy

### Install and update miniconda if galaxy-minimal
- name: Install miniconda for galaxy-minimal
  include_role:
    name: galaxyproject.miniconda
    apply:
      become: true
      become_user: galaxy
  vars:
    miniconda_prefix: '{{ export_dir }}/tool_deps/_conda'
    miniconda_version: 23.9
    miniconda_channels: ['conda-forge', 'bioconda']

### Add selected flavor
- include: restore_flavor.yml
  when: galaxy_flavor != 'galaxy-minimal'

### Setup NGINX
#- include: nginx.yml

- name: Set default job conf
  import_tasks: job_conf.yml
  become: yes
  become_user: galaxy

### Restart all services and start Galaxy
- include: service_restart.yml

- name: Start Galaxy here
  meta: flush_handlers

### Wait Galaxy and Conda
- name: Wait Galaxy
  wait_for:
    host: 127.0.0.1
    port: '4001'
    timeout: 300

- name: Conda lock-file absent
  file:
    path: '{{ tool_deps_path }}/conda.lock'
    state: absent
