- name: Check for java exists in /opt 
  stat: 
    path: /export/tool_deps/_conda
  register: conda
  

- name: upload the python script for database restore 
  become: true
  template:
    src: express-cvmfs-restore.py.j2
    dest: /tmp/express-cvmfs-restore.py
    owner: root
    group: root
    mode: u=rwx,g=rw,o=r
  when: not conda.stat.exists

- name: run python script to restore flavor
  become: true
  command: /tmp/express-cvmfs-restore.py -f {{ galaxy_flavor }} 
  when: not conda.stat.exists
