--- 
#check if conda exist in export to do not extract the file 
#testing phase task

- name: check conda existence 
  stat: 
    path: "/tmp/{{ galaxy_flavor }}"
  register: flavor

- name: upload the python script for database restore 
  become: true
  template:
    src: express-cvmfs-restore.py.j2
    dest: /tmp/express-cvmfs-restore.py
    owner: root
    group: root
    mode: u=rwx,g=rw,o=r
  when: not flavor.stat.exists

- name: run python script to restore flavor
  become: true
  command: /tmp/express-cvmfs-restore.py -f {{ galaxy_flavor }} 
  when: not flavor.stat.exists
