--- 
#check if conda exist in export to do not extract the file 
#testing phase task

- name: check flavor file  existence 
  stat: 
    path: "/tmp/{{ galaxy_flavor }}"
  register: flavor

- name: install ephemeris for workflow installation
  pip:
    name: ephemeris
    virtualenv: '{{ laniakea_galaxy_venv_dir }}'

- name: upload the python script for database restore 
  become: true
  template:
    src: express-cvmfs-restore.py.j2
    dest: /tmp/express-cvmfs-restore.py
    owner: root
    group: root
    mode: u=rwx,g=rw,o=r
  when: not flavor.stat.exists

#- name: create/check destinations
#  file:
#    path: "{{ item }}"
#    state: directory
#    mode: '0755'  
#  with_items:
#    - "{{ tool_deps_path }}"
#    - "{{ shed_tool_destination }}"

- name: run python script to restore flavor
  become: true
  command: /tmp/express-cvmfs-restore.py -f {{ galaxy_flavor }} -v {{ galaxy_flavor_version }} -g {{ galaxy_version }}
  when: not flavor.stat.exists
  register: restore_script

- name: check if dir workflows exists
  stat: 
    path: "/cvmfs/{{ restore_cvmfs_repository }}/dump/{{ galaxy_version }}_{{ galaxy_flavor }}_{{ galaxy_flavor_version }}/workflows"
  register: workflows

- name: install workflows  
  become: true
  become_user: galaxy
  shell: '. {{ laniakea_galaxy_venv_dir }}/bin/activate && workflow-install \
  -w {{ workflows.stat.path }} \ 
  -a {{ GALAXY_ADMIN_API_KEY }} -g http://localhost:80'
  when: workflows.stat.exists
  tags:
    - workflows
