---
# restart services
- name: Restart Galaxy
  systemd:
    name: "{{ 'galaxy' if (uwsgi_mode == 'mule') else 'galaxy-zergling@0'}}"
    state: restarted

- name: Restart proftpd
  systemd:
    name: proftpd
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
