---
- name: 'galaxyctl update (Galaxy >= 23.0)'
  command: "{{ laniakea_galaxy_venv_dir }}/bin/galaxyctl -c {{ laniakea_galaxy_config_file }} update"
  listen: "galaxyctl update"
  become: yes

- name: 'galaxy gravity restart (Galaxy >=23.0)'
  command: "{{ laniakea_galaxy_venv_dir }}/bin/galaxyctl -c {{ laniakea_galaxy_config_file }} graceful"
  listen: "restart galaxy"
  become: yes
